---
- name: Sample playbook
  hosts: container
  # connection: local
  
  tasks:
    - name: Setting host fact
      set_fact:
        one_fact: something
      register: somevar

    - name: Print values from fact
      debug:
        msg: "{{ somevar.ansible_facts.one_fact }}"
    
    - name: Print values from group vars in inventory
      debug: 
        msg: "{{ env }}"
